#if !defined(FONT_DEFS_H)
#define FONT_DEFS_H

enum EGAMEFONT {
    EGAMEFONT_SIZE_40 = 0,
    EGAMEFONT_SIZE_38,
    EGAMEFONT_SIZE_34,
    EGAMEFONT_SIZE_32,
    EGAMEFONT_SIZE_30,
    EGAMEFONT_SIZE_28,
    EGAMEFONT_SIZE_26,
    EGAMEFONT_SIZE_24,
    EGAMEFONT_SIZE_22,
    EGAMEFONT_SIZE_20,
    EGAMEFONT_SIZE_18,
    EGAMEFONT_SIZE_16,
    EGAMEFONT_SIZE_14,
    EGAMEFONT_SIZE_12,
    EGAMEFONT_SIZE_10,
    EGAMEFONT_SIZE_08,
    EGAMEFONT_NUM
};

enum EFONT_LANGUAGE {
    EFONT_LANGUAGE_ENGLISH=0,
    EFONT_LANGUAGE_HANS,
    EFONT_LANGUAGE_HANT,
    EFONT_LANGUAGE_JP,
    EFONT_LANGUAGE_KOREAN,
    EFONT_LANGUAGE_INDONESIAN,
    EFONT_LANGUAGE_THAI,
    EFONT_LANGUAGE_NUM
};

#endif // FONT_DEFS_H
