#if !defined(RYTHM_UI_DEFS_H)
#define RYTHM_UI_DEFS_H

#define RYTHM_UI_SELECTED_FONT_COLOR        RGBA(0xAF,  0xAF,   0xAF,   0xFF)
#define RYTHM_UI_NOT_SELECTED_FONT_COLOR    RGBA(0x4F,  0x4F,   0x4F,   0xFF)
#define RYTHM_UI_BOX_NUMBER_UP_COLOR        RGBA(0xAF,  0xAF,   0xAF,   0xFF)
#define RYTHM_UI_BOX_NUMBER_DOWN_COLOR      RGBA(0x4F,  0x4F,   0x4F,   0xFF)


#define RYTHM_UI_VERTICAL_LINE_COLOR        RGBA(0x7F,  0x7F,   0x7F,   0xFF)

enum EGRAPH_TYPE {
    EGRAPH_CHANNEL=0,
    EGRAPH_INNER,
    EGRAPH_SEMA_3D,
};
#endif // #if !defined(RYTHM_UI_DEFS_H)
